function [countExu, countRed] = getFeatures(images, num_images)
%% 2. Feature Extraction %%
%% Optic disc Loc + Exudate detection using log fuction
for n=1:num_images
    % Find optic disc
    odLoc{n} = opticDiscCH(images{n});
    % Detect exudates using method 1
    exudateImg{n} = exudateDetection(images{n});
    % Remove optic disc
    exudateImg{n} = double(exudateImg{n}) .* ~double(odLoc{n});
    %figure;
    %imagesc(imfuse(images{n},odRemove{n}));
end
%% Display
%for n=1:num_images
    %figure;
    %imagesc(exudateImg{n});
    %colormap(gray);
    %imshowpair(images{n},odLoc{n});
%end
%% Exudate detection using Mean Shift
for n=1:num_images
    imgA = images{n};
    msExudate{n} = exudateDetectionMSNC(imgA);
end
%% Create ring mask
% The aim is to remove the unwanted noise that generally occur on the edge
% of the retina image
for n = 1:num_images
imageTest = images{n};
% BW = imbinarize(I) creates a binary image from 2-D or 3-D grayscale 
% image I by replacing all values above a globally determined threshold
% with 1s and setting all other values to 0s. This is done rather than the
% tradition threshold becouse of a tint on some individual retia images
% channels
imageTest2 = imbinarize(imageTest,0.15);
imageTest2 = medfilt2(imageTest2(:,:,1), [11,11]);
mask = edge(imageTest2, 'sobel');
outerdisk = strel('disk', 15);
imageRing{n} = imdilate(mask, outerdisk);
%figure;
%imagesc(imageRing{n});
end
%% Mask images
% Take the two exudate detected images and mask them with each other and
% the ring image. This removes most of the false positives generated by each method.
for n=1:num_images
    finalExu{n} = msExudate{n} .* exudateImg{n} .* ~imageRing{n};
    %figure
    %imshowpair(images{n},finalExu{n});
end
%% Count exudate pixels
for n=1:num_images
    countExu(n) = sum(sum(finalExu{n} == 1));
end
%% Get red lesions
% Get hemorrages and micro aneurysms
for n=1:num_images
    redLes{n} = redLesDetection(images{n});
end
%% Count red lesion pixels
for n=1:num_images
    countRed(n) = sum(sum(redLes{n} == 1));
end